import pandas as pd
import os

def clean_race_laps(laps_df):
    """
    Takes raw fastf1 laps data and transforms it into a clean, 
    ML-ready feature set of pure racing pace.
    """
    print("System: Starting data cleaning...")
    
    # 1. The 'IsAccurate' filter: fastf1's built-in flag that removes 
    # Safety Cars, VSCs, and extreme anomalies.
    clean_df = laps_df[laps_df['IsAccurate'] == True].copy()
    
    # 2. Drop Pit Laps: Remove any lap where the car entered or exited the pits.
    clean_df = clean_df[(clean_df['PitOutTime'].isnull()) & (clean_df['PitInTime'].isnull())]
    
    # 3. Format Conversion: ML models need numbers, not timestamps. 
    # Convert LapTime to total seconds (e.g., 1:15.500 becomes 75.500)
    clean_df['LapTime_Seconds'] = clean_df['LapTime'].dt.total_seconds()
    
    # 4. Feature Selection: Keep only the columns that hold predictive value.
    features = [
        'Driver', 'LapNumber', 'LapTime_Seconds', 
        'Compound', 'TyreLife', 'Stint'
    ]
    clean_df = clean_df[features]
    
    # 5. Drop any lingering NaNs (missing data) in our target variable
    clean_df = clean_df.dropna(subset=['LapTime_Seconds'])
    
    print(f"Success: Filtered down to {len(clean_df)} pure racing laps.")
    return clean_df

# --- If you are running this in your existing script, you would use it like this: ---
# (Assuming monaco_laps was already generated by your ingestor)
#
# clean_monaco = clean_race_laps(monaco_laps)
# print("\nCleaned ML-Ready Data Preview:")
# print(clean_monaco.head())
def get_fastest_lap_telemetry(raw_laps_df, driver_code):
    """
    Extracts the high-resolution 10Hz car telemetry (Speed, Throttle, Brake) 
    for a specific driver's fastest lap.
    Note: We must pass the RAW fastf1 laps object here, not the cleaned pandas dataframe.
    """
    print(f"System: Extracting high-res telemetry for {driver_code}...")
    
    try:
        # 1. Isolate the driver's fastest lap
        fastest_lap = raw_laps_df.pick_drivers(driver_code).pick_fastest()
        
        # 2. Extract the car's telemetry for that specific lap
        telemetry = fastest_lap.get_telemetry()
        
        # 3. Add the driver code so we know whose data this is when we mix them later
        telemetry['Driver'] = driver_code
        
        # 4. Keep only the ML-relevant columns (dropping things like session time)
        features = ['Driver', 'Distance', 'Speed', 'Throttle', 'Brake', 'nGear', 'RPM' , 'X' , 'Y']
        clean_telemetry = telemetry[features]
        
        print(f"Success: Extracted {len(clean_telemetry)} data points for {driver_code}.")
        return clean_telemetry
        
    except Exception as e:
        print(f"Error extracting telemetry for {driver_code}: {e}")
        return None


def save_to_feature_store(df, folder_name, file_name):
    """
    Saves DataFrames as highly compressed Parquet files.
    This acts as our Data Lake / Feature Store.
    """
    # Create the directory if it doesn't exist
    store_path = f'./feature_store/{folder_name}'
    os.makedirs(store_path, exist_ok=True)
    
    # Save as Parquet
    full_path = f'{store_path}/{file_name}.parquet'
    df.to_parquet(full_path, index=False)
    print(f"System: Saved data to {full_path}")